doc-warnings: false
test-warnings: true
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
  - examples
  - venv
  - ray-appengine
  - ray-peewee
  - ray-sqlalchemy
  - ray-core/tests
python-targets:
  - 2
  - 3
pylint:
  disable:
    - global-variable-not-assigned
    - protected-access
