doc-warnings: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
  - examples
  - venv
  - ray-appengine
  - ray-peewee
  - ray-sqlalchemy
python-targets:
  - 2
  - 3
