language: python

python:
  - 2.7
  - 3.5

before_install:
    - pip install python-coveralls
    - pip install nose
    - pip install -r venv/requirements_tests.txt

    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.38.zip
    - unzip -q google_appengine_1.9.38.zip
    - export PATH=$PATH:/home/travis/build/felipevolpone/ray/google_appengine/
    - export PYTHONPATH="$PYTHONPATH:/home/travis/build/felipevolpone/ray/google_appengine/"

script:
    - cd ray-core
    - pip install . # install ray-core
    - nosetests --tests=tests --with-coverage --cover-package=../ray-core/

    # - cd ..
    # - cd ray-appengine
    # - pip install . # install ray-appengine
    # - nosetests --tests=tests --with-coverage --cover-package=ray_appengine

    # - cd ..
    # - cd ray-sqlalchemy  # install ray-sqlalchemy
    # - pip install .
    # - nosetests --tests=tests --with-coverage --cover-package=ray_sqlalchemy

    - cd ..
    - cd ray-peewee  # install ray-peewee
    - pip install .
    - nosetests --tests=tests --with-coverage --cover-package=ray_peewee

after_success:
  - coveralls
  - cd ../ray-core
  - coveralls --config_file=.coveragerc

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
